# Generated by Django 4.2.5 on 2024-04-13 00:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Subscription',
            fields=[
                ('subcription_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(max_length=200)),
                ('subscription_date', models.DateTimeField(default=datetime.datetime(2024, 4, 13, 0, 2, 46, 389421, tzinfo=datetime.timezone.utc))),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
