# Generated by Django 4.2.5 on 2024-04-13 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_subscription',
            name='subscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 13, 0, 4, 32, 523181, tzinfo=datetime.timezone.utc)),
        ),
    ]
