# Generated by Django 4.2.5 on 2024-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0004_user_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_project',
            name='auto_run',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_project',
            name='total_data',
            field=models.IntegerField(default=0),
        ),
    ]
