# Generated by Django 4.2.5 on 2024-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0005_user_project_auto_run_user_project_total_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_project',
            name='website_link_title',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
    ]
