# Generated by Django 4.2.5 on 2024-04-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0006_user_project_website_link_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Project_Process',
            fields=[
                ('step', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(default=None, max_length=200)),
                ('get_by', models.CharField(default=None, max_length=200)),
                ('attribute_name', models.CharField(default=None, max_length=200)),
                ('user_project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_view.user_project')),
            ],
        ),
    ]
