# Generated by Django 4.2.5 on 2024-04-15 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0007_user_project_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_project',
            name='website_link_title',
        ),
    ]
