# Generated by Django 4.2.5 on 2024-04-20 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_view', '0008_remove_user_project_website_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_project_process',
            name='attribute_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_project_process',
            name='get_by',
            field=models.CharField(default='', max_length=200),
        ),
    ]
